FROM golang:1.12

# Install TensorFlow C library
RUN curl -L \
   "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.12.0.tar.gz" | \
   tar -C "/usr/local" -xz
RUN ldconfig

# Hide some warnings
ENV TF_CPP_MIN_LOG_LEVEL 2

RUN apt-get update && apt-get install -y --no-install-recommends \
		g++ \
		gcc \
		libc6-dev \
		make \
		pkg-config \
    wget \
    curl \
    git \
    unzip \
	&& rm -rf /var/lib/apt/lists/*

# Download InceptionV3 model
RUN mkdir -p /model && \
  wget "https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip" -O /model/inception.zip && \
  unzip /model/inception.zip -d /model && \
  chmod -R 777 /model

ENV GO111MODULE=on

WORKDIR /image-recognition

# dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

EXPOSE 8090

RUN go test ./...
RUN go build
RUN go install

CMD ["captionthis"]
